
# Key Formatting Constructs

The key formatting constructs are discussed at <http://rmarkdown.rstudio.com/authoring_basics.html>. You can see above how I constructed main section headings. Now I'm going to create a series of sections using secondary headings.

## Emphasis

This is *italic*. This is **bold**.

## Superscripts

This is y^2^.

## Lists

### Unordered

* Item 1
* Item 2
    + Item 2a
    + Item 2b
    
### Ordered

1. Item 1
2. Item 2
3. Item 3
    + Item 3a
    + Item 3b

1. Item 1  
2. Item 2  
3. Item 3  
    (a) Item 3a
    (b) Item 3b


## Block Quotes

A friend once said:

> It's always better to give
> than to receive.

## Displaying Blocks of Code Without Evaluating

In some situations, you want to display R code but not evaluate it. Here is an example of how you format.

```
This text is displayed verbatim / preformatted
```

## Displaying R Code Inline in a Sentence

Sometimes, you need to include an R name or command inline in a sentence. Here is how your format it.  

The `sqrt` function computes the square root of a number.

## Evaluating and Inserting R Code in a Sentence

Sometimes, you want a result without showing the user that you used R to get it.
Here is an example.

The mean of the numbers 2,3,4 is `r mean(c(2,3,4))`.

There are lots of ways you can exploit this capability.  You can do more advanced calculations in a hidden code block, assign the results to variables, and then simply use the variable names to insert the results in a sentence.

In the following example, I compute the sum of the integers from 2 to 19 in a hidden code block. Then I display the result inline.

```{r,echo=FALSE}
x <- 2:19
answer <- sum(x)
```
The sum of the integers from 2 to 19 is `r answer`.

## Typesetting Equations

## Inline vs. Display Material

Equations can be formatted *inline* or as *displayed formulas*.  In the latter case, they are centered and set off from the main text.  In the former case, the mathematical material occurs smoothly in the line of text.

In order to fit neatly in a line, summation expressions (and similar constructs) are formatted slightly differently in their inline and display versions.  

Inline mathematical material is set off by the use of single dollar-sign characters. Consequently, if you wish to use a dollar sign (for example, to indicate currency), you need to preface it with a back-slash.  The following examples, followed by their typeset versions, should make this clear

``` 
This summation expression $\sum_{i=1}^n X_i$ appears inline.
```

This summation expression $\sum_{i=1}^n X_i$ appears inline.

```
This summation expression is in display form.
$$\sum_{i=1}^n X_i$$
```
This summation expression is in display form.

$$\sum_{i=1}^n X_i$$


## Some LaTeX Basics

In this section, we show you some rudiments of the LaTeX typesetting language.


### Self-Sizing Parentheses

In LaTeX, you can create parentheses, brackets, and braces which size themselves automatically to contain large expressions. You do this using the `\left` and `\right` operators.  Here is an example

```
$$\sum_{i=1}^{n}\left( \frac{X_i}{Y_i} \right)$$
```

$$\sum_{i=1}^{n}\left( \frac{X_i}{Y_i} \right)$$




### Special Functions

LaTeX typesets special functions in a different font from mathematical variables. These functions, such as $\sin$, $\cos$, etc. are indicated in LaTeX with a backslash. Here is an example that also illustrates how to typeset an integral.

```
$$\int_0^{2\pi} \sin x~dx$$
```
$$\int_0^{2\pi} \sin x~dx$$

### Matrices

Matrics are presented in the `array` environment. One begins with the statement
`\begin{array}` and ends with the statement `\end{array}`. Following the opening statement, a format code is used to indicate the formatting of each column. In the example below, we use the code `{rrr}` to indicate that each column is right justified. Each row is then entered, with cells separated by the `&` symbol, and each line (except the last) terminated by `\\`.

```
$$\begin{array}
{rrr}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}
$$
```
$$\begin{array}
{rrr}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}
$$

In math textbooks, matrices are often surrounded by brackets, and are assigned to a boldface letter.  Here is an example

```
$$\mathbf{X} = \left[\begin{array}
{rrr}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}\right]
$$
```

$$\mathbf{X} = \left[\begin{array}
{rrr}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}\right]
$$
